name: 'IRC Message Action'
description: 'Sends a message to an irc channel'
author: 'Enno Boland'
inputs:
  server:
    description: 'IRC server'
    default: 'chat.freenode.net'
    required: true
  port:
    description: 'IRC server port'
    default: 6697
    required: true
  password:
    description: 'IRC server password'
    required: false
  channel:
    description: 'IRC channel to message'
    required: true
  channel_key:
    description: 'IRC channel password'
    required: false
  nickname:
    description: 'IRC user nickname'
    required: true
  sasl_password:
    description: 'IRC user SASL password'
    required: false
  message:
    description: 'Message to send'
    required: true
  notice:
    description: 'Use NOTICE instead of PRIVMSG'
    default: false
    required: false
  tls:
    description: 'Connect to server using TLS'
    default: true
    required: false
  response_allow_from:
    description: 'Comma seperated list of authenticated accounts allowed to response to an action'
    required: false
  response_timeout:
    description: 'Timeout to wait for a response'
    default: 60
    required: false
outputs:
  response_from:
    description: 'nickname of the responding user'
  response:
    description: 'Response written from an authenticated user'
runs:
  using: 'node12'
  main: 'app.js'
branding:
  icon: 'message-square'
  color: 'yellow'
