name: 'IRC Message Action'
description: |
  This action prints messages to an IRC Channel. Optionally waits for responses.
author: 'Enno Boland'
inputs:
  server:
    description: 'The hostname of the IRC server'
    default: 'irc.libera.chat'
    required: true
  port:
    description: 'The port number of the IRC server'
    default: 6697
    required: true
  channel:
    description: 'IRC channel that will receive the messages'
    required: true
  channel_key:
    description: 'IRC channel password'
    required: false
  nickname:
    description: 'IRC nickname'
    required: true
  sasl_password:
    description: 'IRC SASL password'
    required: false
  message:
    description: 'Message to send'
    required: true
  notice:
    description: 'Use NOTICE instead of PRIVMSG'
    default: false
    required: false
  tls:
    description: 'Use TLS to connect to the IRC server'
    default: true
    required: false
  response_allow_from:
    description: 'Comma seperated list of authenticated accounts allowed to response to an action'
    required: false
  response_timeout:
    description: 'Timeout to wait for a response in seconds'
    default: 60
    required: false
  debug:
    description: 'Enables verbose output.'
    default: false
    required: false
outputs:
  response_from:
    description: 'nickname of the responding user'
  response:
    description: 'Response written from an authenticated user'
runs:
  using: 'node12'
  main: 'app.js'
branding:
  icon: 'hash'
  color: 'gray-dark'
