on: [push]

jobs:
  irc_push:
    runs-on: ubuntu-latest
    name: IRC notification
    steps:
    - name: push notification
      uses: Gottox/irc-message-action
      with:
        channel: '##gottox-test'
        notice: true
        nickname: gottox-test
        tls: true
        message: "${{ github.actor }} pushed ${{ github.event.compare }}"
    - name: Get the output time
      run: echo "Done"
