on: [push]

jobs:
  irc_push:
    runs-on: ubuntu-latest
    name: IRC notifications
    steps:
    - name: test multiline
      uses: Gottox/irc-message-action@master
      with:
        channel: '##gottox-channel'
        nickname: gottox-test
        message: |-
          Hello
          World
    - name: notice
      uses: Gottox/irc-message-action@master
      with:
        channel: '##gottox-channel'
        nickname: gottox-test
        message: "Notice"
        notice: true
    - name: privmsg (ssl)
      uses: Gottox/irc-message-action@master
      with:
        channel: '##gottox-channel'
        nickname: gottox-test
        message: "Privmsg (ssl)"
    - name: privmsg (no ssl)
      uses: Gottox/irc-message-action@master
      with:
        port: 6667
        channel: '##gottox-channel'
        nickname: gottox-test
        message: "Privmsg (no ssl)"
        notice: false
        tls: false
    - name: response
      id: response
      uses: Gottox/irc-message-action@master
      with:
        channel: '##gottox-channel'
        nickname: gottox-test
        message: "response"
        response_allow_from: Gottox
    - name: outputs
      run: echo "<${{ steps.response.outputs.response_from }}> ${{ steps.response.outputs.response }}"
