on: [push]

jobs:
  irc_push:
    runs-on: ubuntu-latest
    name: IRC notifications
    steps:
    - name: notice
      uses: Gottox/irc-message-action@master
      with:
        channel: '##gottox-channel'
        nickname: gottox-test
        message: "Notice"
        notice: true
        tls: true
    - name: privmsg (ssl)
      uses: Gottox/irc-message-action@master
      with:
        channel: '##gottox-channel'
        nickname: gottox-test
        message: "Privmsg (ssl)"
        notice: false
        tls: true
    - name: privmsg (no ssl)
      uses: Gottox/irc-message-action@master
      with:
        port: 6667
        channel: '##gottox-channel'
        nickname: gottox-test
        message: "Privmsg (no ssl)"
        notice: false
        tls: false
