on: [push]

jobs:
  irc_push:
    # runs-on: ubuntu-latest
    name: IRC notification
    steps:
    - name: push notification
      uses: Gottox/irc-message-action@master
      with:
        channel: '##gottox-channel'
        notice: false
        nickname: gottox-test
        tls: true
        message: "${{ github.actor }} pushed ${{ github.event.compare }}"
